<?php
// SPDX-License-Identifier: GPL-3.0-or-later

/**
 * Device display name {extension}-{model}-{mac4} and provisioning DHCP hostname.
 */
class Zts_DeviceNamingService
{
	const SETTING_NAME_MANUAL = 'name_manual';

	/** zts_settings: one-shot {extension}-{model}-{mac4} inventory rename completed. */
	const SETTING_NAMES_EXT_MODEL_MAC4_MIGRATED = 'device_names_ext_model_mac4_migrated';

	/** @deprecated use SETTING_NAMES_EXT_MODEL_MAC4_MIGRATED */
	const SETTING_NAMES_EXT_MODEL_MIGRATED = 'device_names_ext_model_migrated';

	/**
	 * Last four hex digits of normalized MAC (uppercase).
	 *
	 * @param string $mac
	 * @return string
	 */
	public static function macSuffix4($mac)
	{
		$mac = self::normalizeMac($mac);

		return strlen($mac) === 12 ? substr($mac, -4) : '';
	}

	/**
	 * Auto name: {extension}-{model}-{last 4 MAC chars}.
	 *
	 * @param string $extension
	 * @param string $model
	 * @param string $mac
	 * @return string
	 */
	public static function nameWithExtensionAndModel($extension, $model, $mac = '')
	{
		$extension = trim((string) $extension);
		$model = trim((string) $model);
		$suffix = self::macSuffix4($mac);
		if ($extension === '' || $model === '' || $suffix === '')
		{
			return '';
		}

		return $extension.'-'.$model.'-'.$suffix;
	}

	/**
	 * @param string $mac
	 * @return string 12 hex upper
	 */
	public static function normalizeMac($mac)
	{
		return strtoupper(preg_replace('/[^0-9A-Fa-f]/', '', (string) $mac));
	}

	/**
	 * @param array  $device
	 * @param string $existingModel from zts_devices.model when not in POST
	 * @return string
	 */
	public static function modelForNaming(array $device, $existingModel = '')
	{
		$m = isset($device['model']) ? trim((string) $device['model']) : '';
		if ($m === '' || $m === 'T00')
		{
			$m = trim((string) $existingModel);
		}
		if ($m === '' || $m === 'T00')
		{
			$from = zts_model_from_device_name(isset($device['name']) ? $device['name'] : '');
			if ($from !== '')
			{
				$m = $from;
			}
		}
		if ($m === '' || $m === 'T00')
		{
			$m = 'Phone';
		}

		return $m;
	}

	/**
	 * @param array  $device
	 * @param string $existingModel
	 * @return string
	 */
	public static function lineBoundName(array $device, $existingModel = '')
	{
		$extension = self::primaryExtensionFromDevice($device);
		if ($extension === '')
		{
			return '';
		}

		$mac = isset($device['mac']) ? (string) $device['mac'] : '';

		return self::nameWithExtensionAndModel($extension, self::modelForNaming($device, $existingModel), $mac);
	}

	/**
	 * @param array $settings zts_device_settings keywords
	 * @return bool
	 */
	public static function isNameManual(array $settings)
	{
		return isset($settings[self::SETTING_NAME_MANUAL])
			&& (string) $settings[self::SETTING_NAME_MANUAL] === '1';
	}

	/**
	 * Names produced by autoreg or automatic line binding (not user-customized).
	 *
	 * @param string      $name
	 * @param string      $mac
	 * @param string      $model
	 * @param string|null $extension primary line extension when known
	 * @return bool
	 */
	public static function isAutoGeneratedName($name, $mac, $model, $extension = null)
	{
		$name = trim((string) $name);
		$mac = self::normalizeMac($mac);
		if ($name === '' || strlen($mac) !== 12)
		{
			return false;
		}

		if (preg_match('/^Auto-Discovered\b/i', $name))
		{
			return true;
		}

		$model = trim((string) $model);
		$candidates = array();
		if ($model !== '' && $model !== 'T00')
		{
			$candidates[] = $model.'-'.$mac;
		}
		$mac4 = self::macSuffix4($mac);
		if ($extension !== null && trim((string) $extension) !== '')
		{
			$ext = trim((string) $extension);
			$candidates[] = $ext.'-'.$mac;
			if ($model !== '' && $model !== 'T00')
			{
				$candidates[] = $ext.'-'.$model;
				if ($mac4 !== '')
				{
					$candidates[] = $ext.'-'.$model.'-'.$mac4;
				}
			}
		}

		foreach ($candidates as $candidate)
		{
			if (strcasecmp($name, $candidate) === 0)
			{
				return true;
			}
		}

		if (preg_match('/^(.+)-([0-9A-F]{12})$/i', $name, $matches))
		{
			if (strtoupper($matches[2]) !== $mac)
			{
				return false;
			}
			$prefix = trim($matches[1]);
			if ($model !== '' && $model !== 'T00' && strcasecmp($prefix, $model) === 0)
			{
				return true;
			}
			if (preg_match('/^[0-9]+$/', $prefix))
			{
				return true;
			}
		}

		return false;
	}

	/**
	 * Apply {extension}-{model}-{mac4} on save unless name_manual or user typed a custom name.
	 * When the primary line extension changes, auto-rename if the posted name still matches an auto pattern.
	 *
	 * @param array       $device modified in place (name, settings)
	 * @param string      $postedName from form
	 * @param array       $existingSettings
	 * @param string      $existingModel
	 * @param string|null $previousExtension primary line extension before save
	 * @return void
	 */
	public static function resolveNameOnSave(array &$device, $postedName, array $existingSettings = array(), $existingModel = '', $previousExtension = null)
	{
		$postedName = Zts_InputValidator::trimString($postedName);
		$mac = isset($device['mac']) ? (string) $device['mac'] : '';
		$model = self::modelForNaming($device, $existingModel);
		$extension = self::primaryExtensionFromDevice($device);
		$prevExt = $previousExtension !== null ? trim((string) $previousExtension) : '';

		$autoName = self::nameWithExtensionAndModel($extension, $model, $mac);

		if ($prevExt !== '' && $extension !== '' && $prevExt !== $extension
			&& self::isAutoGeneratedName($postedName, $mac, $model, $prevExt))
		{
			if ($autoName !== '')
			{
				$device['name'] = $autoName;
				unset($device['settings'][self::SETTING_NAME_MANUAL]);

				return;
			}
		}

		if ($extension !== '' && $autoName !== '' && strcasecmp($postedName, $autoName) !== 0
			&& preg_match('/^(\d+)-/i', $postedName, $nameExtMatch)
			&& $nameExtMatch[1] !== $extension
			&& self::isAutoGeneratedName($postedName, $mac, $model, $nameExtMatch[1]))
		{
			$device['name'] = $autoName;
			unset($device['settings'][self::SETTING_NAME_MANUAL]);

			return;
		}

		if (self::isNameManual($existingSettings)
			|| (isset($device['settings'][self::SETTING_NAME_MANUAL])
				&& (string) $device['settings'][self::SETTING_NAME_MANUAL] === '1'))
		{
			$device['name'] = $postedName;
			$device['settings'][self::SETTING_NAME_MANUAL] = '1';

			return;
		}

		if ($extension === '' || $autoName === '')
		{
			$device['name'] = $postedName;

			return;
		}

		if ($postedName !== $autoName
			&& !self::isAutoGeneratedName($postedName, $mac, $model, $extension))
		{
			$device['name'] = $postedName;
			$device['settings'][self::SETTING_NAME_MANUAL] = '1';

			return;
		}

		$device['name'] = $autoName;
		unset($device['settings'][self::SETTING_NAME_MANUAL]);
	}

	/**
	 * Run migrateExistingDeviceNames once (install/upgrade) unless $force.
	 *
	 * @param bool $force
	 * @return array{updated:int,manual_marked:int,skipped:int,already_done?:bool}
	 */
	public static function migrateExistingDeviceNamesIfNeeded($force = false)
	{
		if (!$force)
		{
			$moduleSettings = Zts_SettingsRepository::fetchAll();
			if (!empty($moduleSettings[self::SETTING_NAMES_EXT_MODEL_MAC4_MIGRATED]))
			{
				return array(
					'updated' => 0,
					'manual_marked' => 0,
					'skipped' => 0,
					'already_done' => true,
				);
			}
		}

		$stats = self::migrateExistingDeviceNames();
		$moduleSettings = Zts_SettingsRepository::fetchAll();
		$moduleSettings[self::SETTING_NAMES_EXT_MODEL_MAC4_MIGRATED] = '1';
		unset($moduleSettings[self::SETTING_NAMES_EXT_MODEL_MIGRATED]);
		Zts_SettingsRepository::saveAll($moduleSettings);

		return $stats;
	}

	/**
	 * One-time: rename auto-pattern inventory rows to {extension}-{model}-{mac4}.
	 *
	 * @return array{updated:int,manual_marked:int,skipped:int}
	 */
	public static function migrateExistingDeviceNames()
	{
		global $db;

		$stats = array('updated' => 0, 'manual_marked' => 0, 'skipped' => 0);

		$rows = sql('SELECT id FROM zts_devices ORDER BY id', 'getAll', DB_FETCHMODE_ASSOC);
		if (!is_array($rows))
		{
			return $stats;
		}

		foreach ($rows as $row)
		{
			$id = (is_array($row) && isset($row['id'])) ? Zts_InputValidator::trimString($row['id']) : '';
			if ($id === '')
			{
				continue;
			}

			$device = Zts_DeviceRepository::findForEdit($id);
			$settings = isset($device['settings']) && is_array($device['settings']) ? $device['settings'] : array();
			if (self::isNameManual($settings))
			{
				$stats['skipped']++;

				continue;
			}

			$extension = self::primaryExtensionFromDevice($device);
			if ($extension === '')
			{
				$stats['skipped']++;

				continue;
			}

			$name = isset($device['name']) ? trim((string) $device['name']) : '';
			$mac = isset($device['mac']) ? (string) $device['mac'] : '';
			$model = self::modelForNaming($device, isset($device['model']) ? $device['model'] : '');
			$autoName = self::nameWithExtensionAndModel($extension, $model, $mac);

			if ($autoName === '')
			{
				$stats['skipped']++;

				continue;
			}

			if (!self::isAutoGeneratedName($name, $mac, $model, $extension))
			{
				sql("REPLACE INTO zts_device_settings (id, keyword, value)
					VALUES ('".$db->escapeSimple($id)."','".self::SETTING_NAME_MANUAL."','1')");
				$stats['manual_marked']++;

				continue;
			}

			if (strcasecmp($name, $autoName) !== 0)
			{
				sql("UPDATE zts_devices SET name = '".$db->escapeSimple($autoName)."'
					WHERE id = '".$db->escapeSimple($id)."'");
				$stats['updated']++;
			}
		}

		return $stats;
	}

	/**
	 * Extension on the lowest assigned line (lineid).
	 *
	 * @param array $device zts_get_phones_edit shape
	 * @return string
	 */
	public static function primaryExtensionFromDevice(array $device)
	{
		if (!isset($device['lines']) || !is_array($device['lines']))
		{
			return '';
		}

		$lineIds = array_keys($device['lines']);
		sort($lineIds, SORT_NUMERIC);

		foreach ($lineIds as $lineid)
		{
			$line = $device['lines'][$lineid];
			if (!is_array($line))
			{
				continue;
			}
			$pbxDeviceId = isset($line['deviceid']) ? $line['deviceid'] : null;
			if ($pbxDeviceId === null || $pbxDeviceId === '')
			{
				continue;
			}
			$extension = self::extensionForPbxDeviceId($pbxDeviceId);
			if ($extension !== '')
			{
				return $extension;
			}
		}

		return '';
	}

	/**
	 * @param string|int $pbxDeviceId devices.id
	 * @return string SIP extension or devices.dial
	 */
	public static function extensionForPbxDeviceId($pbxDeviceId)
	{
		global $db;

		$pbxDeviceId = Zts_InputValidator::trimString($pbxDeviceId);
		if ($pbxDeviceId === '')
		{
			return '';
		}

		$row = sql("SELECT users.extension, devices.dial
			FROM devices
			LEFT OUTER JOIN users ON devices.user = users.extension
			WHERE devices.id = '".$db->escapeSimple($pbxDeviceId)."'", 'getRow', DB_FETCHMODE_ASSOC);
		if (!is_array($row))
		{
			return '';
		}
		if (!empty($row['extension']))
		{
			return trim((string) $row['extension']);
		}
		if (!empty($row['dial']))
		{
			return trim((string) $row['dial']);
		}

		return '';
	}

	/**
	 * @deprecated use resolveNameOnSave()
	 * @param array $device
	 * @return bool
	 */
	public static function applyLineBoundName(array &$device)
	{
		$before = isset($device['name']) ? $device['name'] : '';
		self::resolveNameOnSave($device, $before, array(), isset($device['model']) ? $device['model'] : '');

		return isset($device['name']) && $device['name'] !== $before;
	}

	/**
	 * DHCP hostname for provisioning (phones_list Name column).
	 *
	 * @param array $device
	 * @return string
	 */
	public static function dhcpHostname(array $device)
	{
		$name = isset($device['name']) ? trim((string) $device['name']) : '';
		if ($name === '')
		{
			return '';
		}

		$name = preg_replace('/[^a-zA-Z0-9.-]/', '', $name);
		if ($name === '')
		{
			return '';
		}

		return substr($name, 0, 63);
	}
}
